---
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!!!!!!

  - name: "Ansible | List all known variables and facts"
    debug:
      var: hostvars[inventory_hostname]     